version: "3.8"

services:
    frontend:
        build:
            context: ./frontend
        container_name: ai-resume-analyzer-next
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        env_file:
            - .env
        environment:
            - NODE_ENV=development
    backend:
        build:
            context: ./backend
        container_name: ai-resume-analyzer-python
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on: []
