version: "3.8"

services:
    backend:
        build:
            context: ./backend
        container_name: ai-resume-analyzer-backend
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on: []
